# pcpsp.run corre el modelo upit, y luego
# el pcpsp en los bloques que quedaron
reset;
option solver cplex;
#option gurobi_options 'presolve 0';
model modelos.mod;
# cargar datos
param name symbolic;
let name:= "newman1";
data (name&"_upit_input.dat");
data (name & "_pcpsp_input.dat");
data (name & "_prec.dat");
# resolver upit
solve UPIT;
# recuperar upit y resolver agendamiento ahí
let setUPIT:= {b in setBL: x_upit[b]=1};
solve PCPSP;